meta:
    blog_name: iamthenameoftheblog
    blog_theme: the-plain
    engine: nunjucks
    userpage: false
    baseurl: "/gitpushblog"

username: geekodour
author: geekodour
repo: gitpushblog

posts_per_page: 3
comments_per_page: 3

comment:
    disabled: false
    isGithub: true
    isDisqus: false
    isGithubAuth: false
    disqus_id: geekodour

others:
   template_cat_posts: true

firebaseConfig:
    apiKey: AIzaSyAZSJ1d1Sr9MnTK-__3D8SrwXjjQf6EML4
    authDomain: myblog-2b0ba.firebaseapp.com
    projectId: myblog-2b0ba
