meta:
    blog_name: iamthenameoftheblog
    blog_theme: gitpushblogdefault
    engine: nunjucks
    userpage: true
    baseurl: ""

username: lukego
author: lukego
repo: blog

posts_per_page: 6
comments_per_page: 3

comment:
    disabled: false
    isGithub: true
    isDisqus: false
    isGithubAuth: true
    disqus_id: geekodour

firebaseConfig:
    apiKey: AIzaSyAZSJ1d1Sr9MnTK-__3D8SrwXjjQf6EML4
    authDomain: myblog-2b0ba.firebaseapp.com
    projectId: myblog-2b0ba
