meta:
    blog_name: iamthenameoftheblog
    blog_theme: KeepSimple20
    engine: nunjucks
    userpage: false
    baseurl: "/gitpushblog"

username: lukego
author: lukego
repo: blog

posts_per_page: 6
comments_per_page: 3

comment:
    disabled: false
    isGithub: true
    isDisqus: false
    isGithubAuth: true
    disqus_id: geekodour

others:
   template_cat_posts: false

firebaseConfig:
    apiKey: AIzaSyAZSJ1d1Sr9MnTK-__3D8SrwXjjQf6EML4
    authDomain: myblog-2b0ba.firebaseapp.com
    projectId: myblog-2b0ba
