meta:
    blog_name: geek blog
    blog_theme: newbulmadefault
    baseurl: /gitpushblog

username: lukego
author: lukego
repo: blog

posts_per_page: 6
comments_per_page: 3

comment:
    disabled: false
    isGithub: true
    isDisqus: false
    isGithubAuth: true
    disqus_id: geekodour

firebaseConfig:
    apiKey: AIzaSyAZSJ1d1Sr9MnTK-__3D8SrwXjjQf6EML4
    authDomain: myblog-2b0ba.firebaseapp.com
    databaseURL: https://myblog-2b0ba.firebaseio.com
    projectId: myblog-2b0ba
    storageBucket: myblog-2b0ba.appspot.com
    messagingSenderId: 20890326099
