meta:
    blog_name: iamthenameoftheblog
    blog_theme: 'default-plain'
    blog_description: 'a simple blog' # optional
    domain: 'geekodour.github.io' # optional, username.github.io or if you use a custom domain then that.
    engine: nunjucks # optional
    userpage: false # is the blog to be hosted in username.github.io ?
    baseurl: gitpushblog # [repository name], if userpage is set to true than baseurl will be ignored because it will be "" anyways.

username: geekodour
author: geekodour # [username of author]
repo: gitpushblog # [repository name], if you're doing this for userpage, this this will be the repository name username.github.io

posts_per_page: 3
comments_per_page: 3

comment:
    disabled: false
    isGithub: true # existing github comments will show up under post
    isDisqus: false
    isGithubAuth: false # if true, comment box appears under posts to comment using the githubapi once authenticated, see issue #74
    disqus_id: geekodour # get your disqus_id from disqus.com

others:
   template_cat_posts: true # if set to true, contents of catagory pages will be generated offline, if false then ajax will be used

# recommended that you DON'T set anything to firebase right now, this is unstable
# disabling firebase also means you should set `isGithubAuth` to false.
# If you still want to test it(it works), then use your firebase credentials
# see issue: https://github.com/geekodour/gitpushblog/issues/74
firebaseConfig:
    apiKey: AIzaSyAZSJ1d1Sr9MnTK-__3D8SrwXjjQf6EML4
    authDomain: myblog-2b0ba.firebaseapp.com
    projectId: myblog-2b0ba
