# Profile links on the left sidebar, leave blank to ignore
social:
  github: geekodour
  #bitbucket: philipj
  hacker_news: geekodour
  #stackexchange: 348619
  #stackoverflow: 348619
  twitter: geekodour
  #facebook: zuck
  #tumblr: animalygifs
  #linkedin: philipjagielski
  #gplus: 110552447039675960964
  #gravatar: 86e6ff8f75f9daef42d53b7f8002fd95
  #flickr: johndoe

# "Hi, I'm _______"
name: Matt Swanson
email: test@example.com
tagline: "weak opinions, strongly held"
