# Theme Settings [THESE ARE JUST SAMPLE FIELDS]
# All these fields are available under the `tc`(theme config) object for all templates and client side javascript too

title:              "Theme Name"
description:        "Theme Description that can be long"
google_verify:      epFgX0s_0RM3Cds9ZBOLyaIUH-o # Put your Google Verification here
google_analytics:   UA-XXXXXXX-X # Put your Google Analytics code

# Site Settings
timezone:           Asia/Kuala_Lumpur # optional

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Leonids
  avatar: leonids-logo.png
  job: "PHP & Ruby Developer"
  bio: "A backend developer who loves design awesome things. Working for RendezvousCheznous atm in Marseille, France."
  email: zourenyuan@gmail.com
  disqus-shortname: renyuanzblog
  twitter: renyuan814 #username
  facebook: #username
  google:
    plus: #username
    analytics: UA-62251910-2
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: geekodour #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: renyuan-zou-69b7038a #username
  xing: #username
  instagram: geekodour
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
